image: gradle:jdk12

before_script:
  - cp "$PROJECT_FILES_PATH/project1/build.gradle" build.gradle

stages:
  - compile
  - test

.shared: &shared
  only:
    refs:
      - branches
    changes:
      - src/**/*
  except:
    refs:
      - initial

compile:
  <<: *shared
  stage: compile
  script:
    - cp "$PROJECT_SCRIPTS_PATH/project1/compile.sh" compile.sh
    - sh compile.sh
  tags:
    - project1
    - compile

compile-for-grading:
  <<: *shared
  stage: compile
  script:
    - cp "$PROJECT_SCRIPTS_PATH/project1/compile-for-grading.sh" compile-for-grading.sh
    - sh compile-for-grading.sh
  tags:
    - project1
    - compile

checkstyle:
  <<: *shared
  stage: test
  script:
    - cp "$PROJECT_SCRIPTS_PATH/project1/checkstyle.sh" checkstyle.sh
    - sh checkstyle.sh
  tags:
    - project1
    - checkstyle

test:
  <<: *shared
  stage: test
  script:
    - cp "$PROJECT_SCRIPTS_PATH/project1/test.sh" test.sh
    - sh test.sh
  tags:
    - project1
    - test
